# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'oneApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for oneApp
  pod 'AppCenter/Crashes', '~> 1.7.1'
  pod 'AppCenter/Analytics', '~> 1.7.1'
  pod 'AppCenterReactNativeShared', '~> 1.6.0'
  pod 'AppCenter/Push', '~> 1.7.1'

  

  platform :ios, '9.0'
  pod 'react-native-video', :path => '../node_modules/react-native-video'

  pod 'react-native-keep-awake', :path => '../node_modules/react-native-keep-awake'

  pod 'react-native-orientation', :path => '../node_modules/react-native-orientation'

  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  pod 'react-native-fetch-blob', :path => '../node_modules/react-native-fetch-blob'

  pod 'react-native-pdf', :path => '../node_modules/react-native-pdf'

  pod 'Picker', :path => '../node_modules/react-native-picker'

  target 'oneAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'oneApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for oneApp-tvOS

  target 'oneApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
